-- #18C-1C — READ-ONLY extract of live public DDL (one statement per row).
-- Run in the PRODUCTION Supabase SQL editor.
-- SELECT only. Do not INSERT / UPDATE / DELETE / ALTER.
--
-- Do NOT open results in Excel (Excel treats UTF-8 as CP949 and corrupts Korean).
-- Do NOT use the old single-cell apply_sql blob — that path mangled UTF-8 on copy.
-- Copy the `ddl` column from the SQL editor. Confirm Korean in the
-- finalize_paid_order row BEFORE any TEST apply.
--
-- Sidecar `ddl_utf8_b64` is ASCII-only UTF-8/base64 of the same ddl (integrity / fallback).
-- It is NOT executed as SQL.

WITH public_rels AS (
  SELECT c.oid, n.nspname, c.relname, c.relkind, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relkind IN ('r', 'p')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_depend d
      JOIN pg_extension e ON e.oid = d.refobjid
      WHERE d.objid = c.oid AND d.deptype = 'e'
    )
),
enum_ddl AS (
  SELECT
    10 AS ord,
    'enum'::text AS class,
    t.typname AS object_name,
    format(
      'CREATE TYPE %I.%I AS ENUM (%s);',
      n.nspname,
      t.typname,
      (
        SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)
        FROM pg_enum e
        WHERE e.enumtypid = t.oid
      )
    ) AS ddl
  FROM pg_type t
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
    AND t.typtype = 'e'
    AND NOT EXISTS (
      SELECT 1
      FROM pg_depend d
      JOIN pg_extension x ON x.oid = d.refobjid
      WHERE d.objid = t.oid AND d.deptype = 'e'
    )
),
table_ddl AS (
  SELECT
    20 AS ord,
    'table'::text AS class,
    r.relname AS object_name,
    format(
      'CREATE TABLE IF NOT EXISTS %I.%I (%s);',
      r.nspname,
      r.relname,
      string_agg(
        format(
          '%I %s%s%s%s',
          a.attname,
          format_type(a.atttypid, a.atttypmod),
          CASE a.attidentity
            WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
            WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
            ELSE ''
          END,
          CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
          CASE
            WHEN a.attidentity <> '' THEN ''
            WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
            ELSE ''
          END
        ),
        ', ' ORDER BY a.attnum
      )
    ) AS ddl
  FROM public_rels r
  JOIN pg_attribute a
    ON a.attrelid = r.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad
    ON ad.adrelid = r.oid AND ad.adnum = a.attnum
  WHERE r.relkind IN ('r', 'p')
  GROUP BY r.oid, r.nspname, r.relname
),
function_ddl AS (
  SELECT
    30 AS ord,
    'function'::text AS class,
    p.proname AS object_name,
    pg_get_functiondef(p.oid) || ';' AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_depend d
      JOIN pg_extension e ON e.oid = d.refobjid
      WHERE d.objid = p.oid AND d.deptype = 'e'
    )
),
constraint_ddl AS (
  SELECT
    CASE con.contype WHEN 'p' THEN 40 WHEN 'u' THEN 41 WHEN 'c' THEN 42 WHEN 'x' THEN 43 ELSE 49 END AS ord,
    'constraint'::text AS class,
    con.conname AS object_name,
    format(
      'ALTER TABLE %I.%I ADD CONSTRAINT %I %s;',
      n.nspname,
      c.relname,
      con.conname,
      pg_get_constraintdef(con.oid, true)
    ) AS ddl
  FROM pg_constraint con
  JOIN pg_class c ON c.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND con.contype IN ('p', 'u', 'c', 'f', 'x')
),
index_ddl AS (
  SELECT
    50 AS ord,
    'index'::text AS class,
    ic.relname AS object_name,
    pg_get_indexdef(i.indexrelid) || ';' AS ddl
  FROM pg_index i
  JOIN pg_class c ON c.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND NOT EXISTS (
      SELECT 1 FROM pg_constraint x WHERE x.conindid = i.indexrelid
    )
),
trigger_ddl AS (
  SELECT
    60 AS ord,
    'trigger'::text AS class,
    t.tgname AS object_name,
    pg_get_triggerdef(t.oid, true) || ';' AS ddl
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND NOT t.tgisinternal
),
rls_ddl AS (
  SELECT
    70 AS ord,
    'rls'::text AS class,
    r.relname AS object_name,
    format(
      'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;%s',
      r.nspname,
      r.relname,
      CASE
        WHEN r.relforcerowsecurity THEN format(' ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;', r.nspname, r.relname)
        ELSE ''
      END
    ) AS ddl
  FROM public_rels r
  WHERE r.relrowsecurity
),
policy_ddl AS (
  SELECT
    80 AS ord,
    'policy'::text AS class,
    pol.policyname AS object_name,
    format(
      'DROP POLICY IF EXISTS %I ON %I.%I; CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;',
      pol.policyname,
      pol.schemaname,
      pol.tablename,
      pol.policyname,
      pol.schemaname,
      pol.tablename,
      CASE WHEN pol.permissive = 'RESTRICTIVE' THEN 'RESTRICTIVE' ELSE 'PERMISSIVE' END,
      pol.cmd,
      (
        SELECT string_agg(
          CASE WHEN role_name = 'public' THEN 'public' ELSE quote_ident(role_name) END,
          ', '
        )
        FROM unnest(pol.roles) AS role_name
      ),
      CASE WHEN pol.qual IS NOT NULL THEN ' USING (' || pol.qual || ')' ELSE '' END,
      CASE WHEN pol.with_check IS NOT NULL THEN ' WITH CHECK (' || pol.with_check || ')' ELSE '' END
    ) AS ddl
  FROM pg_policies pol
  WHERE pol.schemaname = 'public'
),
table_revoke_ddl AS (
  SELECT
    90 AS ord,
    'revoke'::text AS class,
    r.relname AS object_name,
    format(
      'REVOKE ALL ON TABLE %I.%I FROM PUBLIC; REVOKE ALL ON TABLE %I.%I FROM anon; REVOKE ALL ON TABLE %I.%I FROM authenticated; REVOKE ALL ON TABLE %I.%I FROM service_role;',
      r.nspname, r.relname,
      r.nspname, r.relname,
      r.nspname, r.relname,
      r.nspname, r.relname
    ) AS ddl
  FROM public_rels r
),
table_grant_ddl AS (
  SELECT
    91 AS ord,
    'grant'::text AS class,
    (g.table_name || ':' || g.grantee || ':' || g.privilege_type) AS object_name,
    format(
      'GRANT %s ON TABLE %I.%I TO %I;',
      g.privilege_type,
      g.table_schema,
      g.table_name,
      g.grantee
    ) AS ddl
  FROM information_schema.role_table_grants g
  WHERE g.table_schema = 'public'
    AND g.grantee IN ('anon', 'authenticated', 'service_role', 'postgres')
),
routine_grant_ddl AS (
  SELECT DISTINCT
    92 AS ord,
    'grant_fn'::text AS class,
    (r.routine_name || ':' || r.grantee) AS object_name,
    format(
      'GRANT EXECUTE ON FUNCTION %I.%I(%s) TO %I;',
      r.specific_schema,
      r.routine_name,
      COALESCE(pg_get_function_identity_arguments(p.oid), ''),
      r.grantee
    ) AS ddl
  FROM information_schema.routine_privileges r
  JOIN pg_proc p ON p.proname = r.routine_name
  JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = r.specific_schema
  WHERE r.specific_schema = 'public'
    AND r.grantee IN ('anon', 'authenticated', 'service_role', 'postgres')
    AND r.privilege_type = 'EXECUTE'
),
ordered AS (
  SELECT * FROM enum_ddl
  UNION ALL SELECT * FROM table_ddl
  UNION ALL SELECT * FROM function_ddl
  UNION ALL SELECT * FROM constraint_ddl
  UNION ALL SELECT * FROM index_ddl
  UNION ALL SELECT * FROM trigger_ddl
  UNION ALL SELECT * FROM rls_ddl
  UNION ALL SELECT * FROM policy_ddl
  UNION ALL SELECT * FROM table_revoke_ddl
  UNION ALL SELECT * FROM table_grant_ddl
  UNION ALL SELECT * FROM routine_grant_ddl
)
SELECT
  row_number() OVER (ORDER BY ord, object_name, ddl) AS stmt_no,
  class,
  object_name,
  ddl,
  encode(sha256(convert_to(ddl, 'UTF8')), 'hex') AS ddl_sha256_utf8,
  encode(convert_to(ddl, 'UTF8'), 'base64') AS ddl_utf8_b64
FROM ordered
WHERE ddl IS NOT NULL AND length(btrim(ddl)) > 0
ORDER BY stmt_no;
